name: Format, Validate, and Plan

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1

jobs:
  fmt_validate_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: opentofu/setup-opentofu@v1
      - run: tofu init
      - run: tofu fmt -check
      - run: tofu validate
      - run: tofu plan
